-- This SQL file documents the database schema
-- Actual schema is managed by Prisma ORM in backend/prisma/schema.prisma
-- 
-- To apply migrations, use:
-- npm run prisma:push
-- npm run prisma:migrate
--
-- Tables created by Prisma:
-- 1. User - User/Admin accounts
-- 2. Service - Service types with predefined codes
-- 3. ServiceRequest - Client requests for services
-- 4. Quotation - Admin quotations for requests
-- 5. Milestone - Payment milestones within quotations
-- 6. Payment - Payment records with Razorpay integration
-- 7. WorkProgress - Work progress tracking with media
-- 8. Reminder - Automated payment/milestone reminders

-- Enums (Status fields):
-- Role: USER, ADMIN
-- WorkflowStatus: REQUESTED, QUOTED, APPROVED, PAYMENT, IN_PROGRESS, COMPLETED
-- PaymentType: ADVANCE, FULL, MILESTONE
-- PaymentStatus: PENDING, AUTHORIZED, CAPTURED, FAILED, REFUNDED
-- ReminderType: QUOTATION_PENDING, PAYMENT_DUE, PAYMENT_OVERDUE, MILESTONE_COMPLETED, PROJECT_COMPLETED
